apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-sockshop
  namespace: sock-shop
spec:
  acme:
    email: ${LETS_ENCRYPT_EMAIL}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-sockshop
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
