grafana:
  defaultDashboardsTimezone: utc+1
  adminPassword: ${GRAFANA_ADMIN_PASSWORD}

alertmanager:
  config:
    global:
      resolve_timeout: 5m
    inhibit_rules:
    route:
      group_by: ['alertname']
      group_wait: 5s
      group_interval: 1m
      repeat_interval: 10m
      receiver: 'slack-notifications'
      routes:
      
    receivers:
    - name: 'slack-notifications'
      slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '${SLACK_CHANNEL}'
        send_resolved: true
        icon_emoji: ':bell:'
        # title: '{{ .GroupLabels.alertname }}'
        # text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
        text: "<!channel> \nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}\nmessage: {{ .CommonAnnotations.message }}"
    templates:
